"""Registry of UI-managed configuration fields.

Drives the admin Settings UI: groups, types, validation, secret flags,
hot-reloadable flags, and which integration-test probe each field maps to.

Bootstrap-only env vars (DATABASE_URL, REDIS_URL, JWT_SIGNING_SECRET, etc.)
are deliberately NOT listed here — they cannot be edited at runtime.

Adding a new admin-editable setting = add one ConfigField entry. The frontend
form is generated automatically from `/admin/config/schema`.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import Any, Literal


FieldType = Literal[
    "string",
    "secret",
    "int",
    "float",
    "bool",
    "select",
    "json",
    "url",
    "email",
    "textarea",
]


@dataclass
class ConfigField:
    key: str  # canonical env-var-style name, e.g. LLM_DAILY_BUDGET_USD
    settings_attr: str  # corresponding pydantic Settings attr (lowercase)
    group: str  # tab in the UI
    subgroup: str = ""  # collapsible subsection
    label: str = ""
    help: str = ""
    type: FieldType = "string"
    default: Any = None
    options: list[str] | None = None  # for select
    min: float | None = None
    max: float | None = None
    is_secret: bool = False
    hot_reload: bool = True  # if False, change requires worker/poller restart
    test_integration: str | None = None  # key in integration_tests probe map
    advanced: bool = False  # hide behind "Show advanced" toggle


# Tabs are rendered in this order.
GROUPS: list[str] = [
    "LLM Engine",
    "Voice Screening",
    "Email",
    "Channels",
    "Calendar",
    "Meeting Bot",
    "Emotion",
    "Storage",
    "Branding",
    "Compliance",
    "Feature Flags",
]


# ---------------------------------------------------------------------------
# Field registry
# ---------------------------------------------------------------------------

FIELDS: list[ConfigField] = [
    # ---------------- LLM Engine ----------------
    ConfigField(
        key="LLM_PROVIDER",
        settings_attr="llm_provider",
        group="LLM Engine",
        subgroup="Provider",
        label="LLM provider",
        help="Routes through LiteLLM. Switch providers without touching code.",
        type="select",
        options=["openai", "anthropic", "groq", "ollama"],
        default="openai",
        test_integration="llm",
    ),
    ConfigField(
        key="OPENAI_API_KEY",
        settings_attr="openai_api_key",
        group="LLM Engine",
        subgroup="Provider",
        label="OpenAI API key",
        help="Required when provider=openai. Starts with sk-.",
        type="secret",
        is_secret=True,
        test_integration="openai",
    ),
    ConfigField(
        key="ANTHROPIC_API_KEY",
        settings_attr="anthropic_api_key",
        group="LLM Engine",
        subgroup="Provider",
        label="Anthropic API key",
        help="Required when provider=anthropic.",
        type="secret",
        is_secret=True,
        test_integration="anthropic",
    ),
    ConfigField(
        key="GROQ_API_KEY",
        settings_attr="groq_api_key",
        group="LLM Engine",
        subgroup="Provider",
        label="Groq API key",
        type="secret",
        is_secret=True,
        test_integration="groq",
    ),
    ConfigField(
        key="OLLAMA_BASE_URL",
        settings_attr="ollama_base_url",
        group="LLM Engine",
        subgroup="Provider",
        label="Ollama base URL",
        help="For local LLM. e.g. http://ollama:11434",
        type="url",
        advanced=True,
    ),
    ConfigField(
        key="LLM_MODEL_FAST",
        settings_attr="llm_model_fast",
        group="LLM Engine",
        subgroup="Models",
        label="Fast model (screening generation)",
        help="LiteLLM-prefixed. e.g. openai/gpt-4o-mini, groq/llama-3.3-70b-versatile.",
        default="openai/gpt-4o-mini",
    ),
    ConfigField(
        key="LLM_MODEL_SMART",
        settings_attr="llm_model_smart",
        group="LLM Engine",
        subgroup="Models",
        label="Smart model (evaluation, journey reports)",
        help="More capable model. e.g. openai/gpt-4o, anthropic/claude-sonnet-4-6.",
        default="openai/gpt-4o",
    ),
    ConfigField(
        key="LLM_DAILY_CALL_LIMIT",
        settings_attr="llm_daily_call_limit",
        group="LLM Engine",
        subgroup="Limits",
        label="Daily call limit",
        type="int",
        default=2000,
        min=0,
        max=1_000_000,
    ),
    ConfigField(
        key="LLM_DAILY_TOKEN_LIMIT",
        settings_attr="llm_daily_token_limit",
        group="LLM Engine",
        subgroup="Limits",
        label="Daily token limit",
        type="int",
        default=5_000_000,
        min=0,
    ),
    ConfigField(
        key="LLM_PER_CANDIDATE_MONTHLY_LIMIT",
        settings_attr="llm_per_candidate_monthly_limit",
        group="LLM Engine",
        subgroup="Limits",
        label="Per-candidate monthly limit",
        type="int",
        default=40,
        min=0,
    ),
    ConfigField(
        key="LLM_RATE_LIMIT_PER_MINUTE",
        settings_attr="llm_rate_limit_per_minute",
        group="LLM Engine",
        subgroup="Limits",
        label="Rate limit (calls/min)",
        type="int",
        default=60,
        min=0,
    ),
    ConfigField(
        key="LLM_DAILY_BUDGET_USD",
        settings_attr="llm_daily_budget_usd",
        group="LLM Engine",
        subgroup="Limits",
        label="Daily budget (USD)",
        help="Soft cap. Warns at 80%, blocks at 2x.",
        type="float",
        default=20.0,
        min=0,
    ),
    ConfigField(
        key="LANGFUSE_PUBLIC_KEY",
        settings_attr="langfuse_public_key",
        group="LLM Engine",
        subgroup="Tracing",
        label="Langfuse public key",
        type="secret",
        is_secret=True,
        advanced=True,
    ),
    ConfigField(
        key="LANGFUSE_SECRET_KEY",
        settings_attr="langfuse_secret_key",
        group="LLM Engine",
        subgroup="Tracing",
        label="Langfuse secret key",
        type="secret",
        is_secret=True,
        advanced=True,
    ),
    ConfigField(
        key="LANGFUSE_HOST",
        settings_attr="langfuse_host",
        group="LLM Engine",
        subgroup="Tracing",
        label="Langfuse host",
        type="url",
        default="http://localhost:3000",
        advanced=True,
    ),

    # ---------------- Voice Screening ----------------
    ConfigField(
        key="ENABLE_VOICE_SCREENING",
        settings_attr="enable_voice_screening",
        group="Voice Screening",
        label="Enable voice screening round",
        type="bool",
        default=False,
    ),
    ConfigField(
        key="ELEVENLABS_API_KEY",
        settings_attr="elevenlabs_api_key",
        group="Voice Screening",
        subgroup="ElevenLabs",
        label="ElevenLabs API key",
        type="secret",
        is_secret=True,
        test_integration="elevenlabs",
    ),
    ConfigField(
        key="ELEVENLABS_AGENT_ID",
        settings_attr="elevenlabs_agent_id",
        group="Voice Screening",
        subgroup="ElevenLabs",
        label="Agent ID",
    ),
    ConfigField(
        key="ELEVENLABS_PHONE_NUMBER_ID",
        settings_attr="elevenlabs_phone_number_id",
        group="Voice Screening",
        subgroup="ElevenLabs",
        label="Phone number ID",
    ),
    ConfigField(
        key="ELEVENLABS_WEBHOOK_SECRET",
        settings_attr="elevenlabs_webhook_secret",
        group="Voice Screening",
        subgroup="ElevenLabs",
        label="Webhook secret",
        type="secret",
        is_secret=True,
    ),
    ConfigField(
        key="VOICE_AGENT_COMPANY_NAME",
        settings_attr="voice_agent_company_name",
        group="Voice Screening",
        subgroup="Behavior",
        label="Company name (announced in calls)",
        default="GrabOn",
    ),
    ConfigField(
        key="VOICE_AGENT_MAX_CALL_SECONDS",
        settings_attr="voice_agent_max_call_seconds",
        group="Voice Screening",
        subgroup="Behavior",
        label="Max call length (seconds)",
        type="int",
        default=1200,
        min=60,
        max=3600,
    ),
    ConfigField(
        key="VOICE_AGENT_MAX_QUESTIONS",
        settings_attr="voice_agent_max_questions",
        group="Voice Screening",
        subgroup="Behavior",
        label="Max generated questions per call",
        type="int",
        default=3,
        min=1,
        max=10,
    ),
    ConfigField(
        key="VOICE_AGENT_PASS_THRESHOLD",
        settings_attr="voice_agent_pass_threshold",
        group="Voice Screening",
        subgroup="Behavior",
        label="Pass threshold (knockout score)",
        type="int",
        default=65,
        min=0,
        max=100,
    ),
    ConfigField(
        key="VOICE_AGENT_MAX_CALLBACK_ATTEMPTS",
        settings_attr="voice_agent_max_callback_attempts",
        group="Voice Screening",
        subgroup="Behavior",
        label="Max callback attempts",
        type="int",
        default=3,
        min=0,
        max=10,
    ),
    ConfigField(
        key="VOICE_AGENT_MAX_NOANSWER_ATTEMPTS",
        settings_attr="voice_agent_max_noanswer_attempts",
        group="Voice Screening",
        subgroup="Behavior",
        label="Max no-answer retries",
        type="int",
        default=3,
        min=0,
        max=10,
    ),
    ConfigField(
        key="VOICE_AGENT_NOANSWER_BACKOFF_SECONDS",
        settings_attr="voice_agent_noanswer_backoff_seconds",
        group="Voice Screening",
        subgroup="Behavior",
        label="No-answer backoff base (seconds)",
        type="int",
        default=1800,
        min=60,
    ),
    ConfigField(
        key="VOICE_CALL_WINDOW_START_HOUR",
        settings_attr="voice_call_window_start_hour",
        group="Voice Screening",
        subgroup="Quiet hours",
        label="Window start hour (0-23)",
        type="int",
        default=11,
        min=0,
        max=23,
    ),
    ConfigField(
        key="VOICE_CALL_WINDOW_END_HOUR",
        settings_attr="voice_call_window_end_hour",
        group="Voice Screening",
        subgroup="Quiet hours",
        label="Window end hour (0-23)",
        type="int",
        default=20,
        min=0,
        max=23,
    ),
    ConfigField(
        key="VOICE_CALL_WINDOW_TZ",
        settings_attr="voice_call_window_tz",
        group="Voice Screening",
        subgroup="Quiet hours",
        label="Timezone (IANA)",
        default="Asia/Kolkata",
    ),
    ConfigField(
        key="VOICE_CALL_SKIP_WEEKENDS",
        settings_attr="voice_call_skip_weekends",
        group="Voice Screening",
        subgroup="Quiet hours",
        label="Skip weekends",
        type="bool",
        default=False,
    ),

    # ---------------- Email ----------------
    ConfigField(
        key="EMAIL_PROVIDER",
        settings_attr="email_provider",
        group="Email",
        subgroup="Outbound",
        label="Outbound provider",
        type="select",
        options=["auto", "graph", "resend", "smtp"],
        default="auto",
        help="auto picks the first configured: Graph -> Resend -> SMTP.",
    ),
    ConfigField(
        key="RESEND_API_KEY",
        settings_attr="resend_api_key",
        group="Email",
        subgroup="Outbound (Resend)",
        label="Resend API key",
        type="secret",
        is_secret=True,
        test_integration="resend",
    ),
    ConfigField(
        key="RESEND_FROM_EMAIL",
        settings_attr="resend_from_email",
        group="Email",
        subgroup="Outbound (Resend)",
        label="Default from address",
        type="email",
        default="careers@grabon.in",
    ),
    ConfigField(
        key="RESEND_FROM_NAME",
        settings_attr="resend_from_name",
        group="Email",
        subgroup="Outbound (Resend)",
        label="From name",
        default="GrabOn Careers",
    ),
    ConfigField(
        key="RESEND_REPLY_TO",
        settings_attr="resend_reply_to",
        group="Email",
        subgroup="Outbound (Resend)",
        label="Reply-to address",
        type="email",
        default="careers@grabon.in",
    ),
    ConfigField(
        key="ADMIN_NOTIFY_EMAIL",
        settings_attr="admin_notify_email",
        group="Email",
        subgroup="Outbound (Resend)",
        label="Admin notification address",
        type="email",
    ),
    ConfigField(
        key="EMAIL_FROM_TECHNICAL",
        settings_attr="email_from_technical",
        group="Email",
        subgroup="Per-round senders",
        label="Technical panel sender",
        type="email",
    ),
    ConfigField(
        key="EMAIL_FROM_CEO",
        settings_attr="email_from_ceo",
        group="Email",
        subgroup="Per-round senders",
        label="CEO sender",
        type="email",
    ),
    ConfigField(
        key="EMAIL_FROM_HR",
        settings_attr="email_from_hr",
        group="Email",
        subgroup="Per-round senders",
        label="HR sender",
        type="email",
    ),
    ConfigField(
        key="SMTP_HOST",
        settings_attr="smtp_host",
        group="Email",
        subgroup="SMTP fallback",
        label="SMTP host",
        advanced=True,
    ),
    ConfigField(
        key="SMTP_PORT",
        settings_attr="smtp_port",
        group="Email",
        subgroup="SMTP fallback",
        label="SMTP port",
        type="int",
        default=1025,
        advanced=True,
    ),
    ConfigField(
        key="SMTP_USER",
        settings_attr="smtp_user",
        group="Email",
        subgroup="SMTP fallback",
        label="SMTP username",
        advanced=True,
    ),
    ConfigField(
        key="SMTP_PASSWORD",
        settings_attr="smtp_password",
        group="Email",
        subgroup="SMTP fallback",
        label="SMTP password",
        type="secret",
        is_secret=True,
        advanced=True,
    ),
    ConfigField(
        key="SMTP_USE_TLS",
        settings_attr="smtp_use_tls",
        group="Email",
        subgroup="SMTP fallback",
        label="Use TLS",
        type="bool",
        default=False,
        advanced=True,
    ),
    ConfigField(
        key="MAIL_INBOXES",
        settings_attr="mail_inboxes",
        group="Email",
        subgroup="Inbound (IMAP polling)",
        label="Inbox configs (JSON array)",
        help='[{"label":"gmail-careers","host":"imap.gmail.com","port":993,"user":"...","password":"...","source":"gmail","folder":"INBOX"}]',
        type="json",
        is_secret=True,  # contains app passwords
        hot_reload=False,
    ),
    ConfigField(
        key="MAIL_POLL_INTERVAL_SECONDS",
        settings_attr="mail_poll_interval_seconds",
        group="Email",
        subgroup="Inbound (IMAP polling)",
        label="Poll interval (seconds)",
        type="int",
        default=60,
        min=10,
        hot_reload=False,
    ),
    ConfigField(
        key="MAIL_MAX_MESSAGES_PER_POLL",
        settings_attr="mail_max_messages_per_poll",
        group="Email",
        subgroup="Inbound (IMAP polling)",
        label="Max messages per poll",
        type="int",
        default=25,
        min=1,
    ),

    # ---------------- Channels ----------------
    ConfigField(
        key="ENABLE_WHATSAPP",
        settings_attr="enable_whatsapp",
        group="Channels",
        subgroup="WhatsApp",
        label="Enable WhatsApp",
        type="bool",
        default=True,
    ),
    ConfigField(
        key="WHATSAPP_ACCESS_TOKEN",
        settings_attr="whatsapp_access_token",
        group="Channels",
        subgroup="WhatsApp",
        label="Access token",
        type="secret",
        is_secret=True,
        test_integration="whatsapp",
    ),
    ConfigField(
        key="WHATSAPP_PHONE_NUMBER_ID",
        settings_attr="whatsapp_phone_number_id",
        group="Channels",
        subgroup="WhatsApp",
        label="Phone number ID",
    ),
    ConfigField(
        key="WHATSAPP_BUSINESS_ACCOUNT_ID",
        settings_attr="whatsapp_business_account_id",
        group="Channels",
        subgroup="WhatsApp",
        label="Business account ID",
    ),
    ConfigField(
        key="WHATSAPP_WEBHOOK_VERIFY_TOKEN",
        settings_attr="whatsapp_webhook_verify_token",
        group="Channels",
        subgroup="WhatsApp",
        label="Webhook verify token",
        type="secret",
        is_secret=True,
    ),
    ConfigField(
        key="WHATSAPP_APP_SECRET",
        settings_attr="whatsapp_app_secret",
        group="Channels",
        subgroup="WhatsApp",
        label="App secret",
        type="secret",
        is_secret=True,
    ),
    ConfigField(
        key="ENABLE_SMS_REMINDERS",
        settings_attr="enable_sms_reminders",
        group="Channels",
        subgroup="SMS (MSG91)",
        label="Enable SMS reminders",
        type="bool",
        default=True,
    ),
    ConfigField(
        key="MSG91_AUTH_KEY",
        settings_attr="msg91_auth_key",
        group="Channels",
        subgroup="SMS (MSG91)",
        label="MSG91 auth key",
        type="secret",
        is_secret=True,
        test_integration="msg91",
    ),
    ConfigField(
        key="MSG91_SENDER_ID",
        settings_attr="msg91_sender_id",
        group="Channels",
        subgroup="SMS (MSG91)",
        label="Sender ID",
        default="GRABON",
    ),
    ConfigField(
        key="MSG91_TEMPLATE_ID_REMINDER",
        settings_attr="msg91_template_id_reminder",
        group="Channels",
        subgroup="SMS (MSG91)",
        label="Reminder template ID",
    ),
    ConfigField(
        key="TEAMS_WEBHOOK_HR",
        settings_attr="teams_webhook_hr",
        group="Channels",
        subgroup="Teams",
        label="HR channel webhook",
        type="secret",
        is_secret=True,
        test_integration="teams_hr",
    ),
    ConfigField(
        key="TEAMS_WEBHOOK_ALERTS",
        settings_attr="teams_webhook_alerts",
        group="Channels",
        subgroup="Teams",
        label="Alerts channel webhook",
        type="secret",
        is_secret=True,
        test_integration="teams_alerts",
    ),

    # ---------------- Calendar ----------------
    ConfigField(
        key="GRAPH_TENANT_ID",
        settings_attr="graph_tenant_id",
        group="Calendar",
        subgroup="Microsoft Graph",
        label="Tenant ID",
    ),
    ConfigField(
        key="GRAPH_CLIENT_ID",
        settings_attr="graph_client_id",
        group="Calendar",
        subgroup="Microsoft Graph",
        label="Client ID",
    ),
    ConfigField(
        key="GRAPH_CLIENT_SECRET",
        settings_attr="graph_client_secret",
        group="Calendar",
        subgroup="Microsoft Graph",
        label="Client secret",
        type="secret",
        is_secret=True,
        test_integration="graph",
    ),
    ConfigField(
        key="GRAPH_ORGANISER_EMAIL",
        settings_attr="graph_organiser_email",
        group="Calendar",
        subgroup="Microsoft Graph",
        label="Organiser email",
        type="email",
    ),
    ConfigField(
        key="GRAPH_WEBHOOK_CLIENT_STATE",
        settings_attr="graph_webhook_client_state",
        group="Calendar",
        subgroup="Microsoft Graph",
        label="Webhook client state",
        type="secret",
        is_secret=True,
        advanced=True,
    ),
    ConfigField(
        key="GOOGLE_CALENDAR_SERVICE_ACCOUNT_JSON",
        settings_attr="google_calendar_service_account_json",
        group="Calendar",
        subgroup="Google Calendar",
        label="Service account JSON",
        type="textarea",
        is_secret=True,
        test_integration="google_calendar",
    ),
    ConfigField(
        key="GOOGLE_CALENDAR_IMPERSONATE_USER",
        settings_attr="google_calendar_impersonate_user",
        group="Calendar",
        subgroup="Google Calendar",
        label="Impersonate user",
        type="email",
    ),
    ConfigField(
        key="CALCOM_API_KEY",
        settings_attr="calcom_api_key",
        group="Calendar",
        subgroup="Cal.com",
        label="API key",
        type="secret",
        is_secret=True,
        test_integration="calcom",
    ),
    ConfigField(
        key="CALCOM_BASE_URL",
        settings_attr="calcom_base_url",
        group="Calendar",
        subgroup="Cal.com",
        label="Base URL",
        type="url",
        default="https://cal.com",
        advanced=True,
    ),

    # ---------------- Meeting Bot ----------------
    ConfigField(
        key="ENABLE_MEETING_ANALYSIS",
        settings_attr="enable_meeting_analysis",
        group="Meeting Bot",
        label="Enable meeting analysis",
        type="bool",
        default=False,
    ),
    ConfigField(
        key="MEETING_BOT_PROVIDER",
        settings_attr="meeting_bot_provider",
        group="Meeting Bot",
        label="Provider",
        type="select",
        options=["readai", "recall", "graph"],
        default="readai",
    ),
    ConfigField(
        key="READ_AI_API_KEY",
        settings_attr="read_ai_api_key",
        group="Meeting Bot",
        subgroup="Read.ai",
        label="API key",
        type="secret",
        is_secret=True,
    ),
    ConfigField(
        key="READ_AI_BASE_URL",
        settings_attr="read_ai_base_url",
        group="Meeting Bot",
        subgroup="Read.ai",
        label="Base URL",
        type="url",
        default="https://api.read.ai/v1",
        advanced=True,
    ),
    ConfigField(
        key="READ_AI_WEBHOOK_SECRET",
        settings_attr="read_ai_webhook_secret",
        group="Meeting Bot",
        subgroup="Read.ai",
        label="Webhook secret",
        type="secret",
        is_secret=True,
    ),
    ConfigField(
        key="READ_AI_ORGANISER_EMAIL",
        settings_attr="read_ai_organiser_email",
        group="Meeting Bot",
        subgroup="Read.ai",
        label="Organiser mailbox connected to Read.ai",
        type="email",
    ),
    ConfigField(
        key="READ_AI_POLL_DELAY_SECONDS",
        settings_attr="read_ai_poll_delay_seconds",
        group="Meeting Bot",
        subgroup="Read.ai",
        label="Poll delay after meeting start (seconds)",
        type="int",
        default=4200,
        min=0,
        advanced=True,
    ),
    ConfigField(
        key="READ_AI_POLL_MAX_ATTEMPTS",
        settings_attr="read_ai_poll_max_attempts",
        group="Meeting Bot",
        subgroup="Read.ai",
        label="Poll max attempts",
        type="int",
        default=12,
        min=1,
        advanced=True,
    ),
    ConfigField(
        key="READ_AI_POLL_INTERVAL_SECONDS",
        settings_attr="read_ai_poll_interval_seconds",
        group="Meeting Bot",
        subgroup="Read.ai",
        label="Poll interval (seconds)",
        type="int",
        default=300,
        min=30,
        advanced=True,
    ),
    ConfigField(
        key="RECALL_AI_API_KEY",
        settings_attr="recall_ai_api_key",
        group="Meeting Bot",
        subgroup="Recall.ai",
        label="API key",
        type="secret",
        is_secret=True,
        test_integration="recall",
    ),
    ConfigField(
        key="RECALL_AI_BASE_URL",
        settings_attr="recall_ai_base_url",
        group="Meeting Bot",
        subgroup="Recall.ai",
        label="Base URL",
        type="url",
        default="https://us-east-1.recall.ai/api/v1",
        advanced=True,
    ),
    ConfigField(
        key="RECALL_AI_WEBHOOK_SECRET",
        settings_attr="recall_ai_webhook_secret",
        group="Meeting Bot",
        subgroup="Recall.ai",
        label="Webhook secret",
        type="secret",
        is_secret=True,
    ),
    ConfigField(
        key="RECALL_BOT_DISPLAY_NAME",
        settings_attr="recall_bot_display_name",
        group="Meeting Bot",
        subgroup="Recall.ai",
        label="Bot display name",
        default="GrabOn AI Notetaker",
    ),
    ConfigField(
        key="RECALL_BOT_JOIN_LEAD_SECONDS",
        settings_attr="recall_bot_join_lead_seconds",
        group="Meeting Bot",
        subgroup="Recall.ai",
        label="Bot join lead time (seconds)",
        type="int",
        default=120,
        min=0,
    ),
    ConfigField(
        key="GRAPH_TRANSCRIPTS_ENABLED",
        settings_attr="graph_transcripts_enabled",
        group="Meeting Bot",
        subgroup="Graph fallback",
        label="Enable Graph transcripts",
        type="bool",
        default=False,
    ),

    # ---------------- Emotion ----------------
    ConfigField(
        key="EMOTION_MODEL_PROVIDER",
        settings_attr="emotion_model_provider",
        group="Emotion",
        label="Provider",
        type="select",
        options=["wav2vec2", "sensevoice", "disabled"],
        default="wav2vec2",
    ),
    ConfigField(
        key="EMOTION_MODEL_ENDPOINT",
        settings_attr="emotion_model_endpoint",
        group="Emotion",
        label="Service endpoint",
        type="url",
        help="Base URL of emotion microservice. e.g. http://emotion:8090",
        test_integration="emotion",
    ),
    ConfigField(
        key="EMOTION_API_KEY",
        settings_attr="emotion_api_key",
        group="Emotion",
        label="Bearer token",
        type="secret",
        is_secret=True,
    ),

    # ---------------- Storage ----------------
    ConfigField(
        key="R2_ACCESS_KEY_ID",
        settings_attr="r2_access_key_id",
        group="Storage",
        subgroup="Object storage",
        label="Access key ID",
        type="secret",
        is_secret=True,
        test_integration="r2",
    ),
    ConfigField(
        key="R2_SECRET_ACCESS_KEY",
        settings_attr="r2_secret_access_key",
        group="Storage",
        subgroup="Object storage",
        label="Secret access key",
        type="secret",
        is_secret=True,
    ),
    ConfigField(
        key="R2_BUCKET_RESUMES",
        settings_attr="r2_bucket_resumes",
        group="Storage",
        subgroup="Object storage",
        label="Resumes bucket",
        default="hiring-agent-resumes",
    ),
    ConfigField(
        key="R2_BUCKET_CONSENT",
        settings_attr="r2_bucket_consent",
        group="Storage",
        subgroup="Object storage",
        label="Consent bucket",
        default="hiring-agent-consent",
    ),
    ConfigField(
        key="R2_REGION",
        settings_attr="r2_region",
        group="Storage",
        subgroup="Object storage",
        label="Region",
        default="auto",
        advanced=True,
    ),
    ConfigField(
        key="R2_PUBLIC_ENDPOINT_URL",
        settings_attr="r2_public_endpoint_url",
        group="Storage",
        subgroup="Object storage",
        label="Public endpoint (for browser-facing URLs)",
        type="url",
        advanced=True,
    ),

    # ---------------- Branding ----------------
    ConfigField(
        key="APP_BASE_URL",
        settings_attr="app_base_url",
        group="Branding",
        label="Backend public URL",
        type="url",
        default="http://localhost:8000",
    ),
    ConfigField(
        key="FRONTEND_BASE_URL",
        settings_attr="frontend_base_url",
        group="Branding",
        label="Frontend public URL (used in candidate emails)",
        type="url",
        default="http://localhost:3100",
    ),
    ConfigField(
        key="SCREENING_URL_TTL_DAYS",
        settings_attr="screening_url_ttl_days",
        group="Branding",
        label="Screening link TTL (days)",
        type="int",
        default=14,
        min=1,
        max=180,
    ),

    # ---------------- Compliance ----------------
    ConfigField(
        key="DATA_RETENTION_DAYS_DEFAULT",
        settings_attr="data_retention_days_default",
        group="Compliance",
        label="Default retention (days)",
        help="Candidates and applications older than this are purged.",
        type="int",
        default=180,
        min=30,
    ),
    ConfigField(
        key="DATA_RETENTION_DAYS_TALENT_POOL",
        settings_attr="data_retention_days_talent_pool",
        group="Compliance",
        label="Talent pool retention (days)",
        help="Opted-in cold pool retention.",
        type="int",
        default=540,
        min=30,
    ),
    ConfigField(
        key="DPO_CONTACT_EMAIL",
        settings_attr="dpo_contact_email",
        group="Compliance",
        label="DPO contact email",
        type="email",
        default="dpo@grabon.in",
    ),

    # ---------------- Feature Flags ----------------
    ConfigField(
        key="ENABLE_ASSESSMENT_ROUND",
        settings_attr="enable_assessment_round",
        group="Feature Flags",
        label="Enable assessment round (PI Cognitive)",
        type="bool",
        default=False,
    ),
    ConfigField(
        key="ENABLE_CEO_DASHBOARD",
        settings_attr="enable_ceo_dashboard",
        group="Feature Flags",
        label="Enable CEO dashboard",
        type="bool",
        default=False,
    ),
    ConfigField(
        key="AUTO_APPROVE_GREEN_TIER",
        settings_attr="auto_approve_green_tier",
        group="Feature Flags",
        label="Auto-approve green-tier candidates",
        help="Skip HR review for top-tier candidates.",
        type="bool",
        default=False,
    ),
    ConfigField(
        key="ENABLE_VOICE_MEETING_CONFIRMATION",
        settings_attr="enable_voice_meeting_confirmation",
        group="Feature Flags",
        label="Voice for meeting confirmations",
        help="Use voice agent for slot confirmation/reminders (default: email only).",
        type="bool",
        default=False,
    ),
]


# ---------------------------------------------------------------------------
# Lookups
# ---------------------------------------------------------------------------

_BY_KEY: dict[str, ConfigField] = {f.key: f for f in FIELDS}
_BY_ATTR: dict[str, ConfigField] = {f.settings_attr: f for f in FIELDS}


def get_field(key: str) -> ConfigField | None:
    return _BY_KEY.get(key)


def get_field_by_attr(attr: str) -> ConfigField | None:
    return _BY_ATTR.get(attr)


def all_keys() -> list[str]:
    return list(_BY_KEY.keys())


def secret_keys() -> set[str]:
    return {f.key for f in FIELDS if f.is_secret}


def fields_for_group(group: str) -> list[ConfigField]:
    return [f for f in FIELDS if f.group == group]


def schema_payload() -> dict[str, Any]:
    """JSON-serializable schema for the frontend form generator."""
    groups: dict[str, dict[str, Any]] = {}
    for g in GROUPS:
        groups[g] = {"name": g, "fields": []}
    for f in FIELDS:
        d = asdict(f)
        groups.setdefault(f.group, {"name": f.group, "fields": []})
        groups[f.group]["fields"].append(d)
    return {"groups": [groups[g] for g in GROUPS]}
